#!/bin/sh
# Use yapf to formatting python code

echo "Running pre-push check..."

function checkFailed {
	echo -e "\e[31;1mError\e[0m: ""$1"
	echo ""
	echo -e "Pre-push check \e[31;1mfailed\e[0m."
	echo ""
	exit 1
}

git diff-index --quiet HEAD --
if [ "$?" -ne 0 ]; then
	checkFailed "Work tree not clean."
fi

remote="$1"
if [ "$remote" = "" ]; then
	remote='origin'
fi
format_exec="tool/format"

$format_exec $remote --check
if [ "$?" -ne 0 ]; then
	checkFailed  'Please run |tool/format {remote}| before
|git push {remote} {branch}|'
fi

echo ""
echo -e "Pre-push check \e[32;1msuccess\e[0m."
echo ""
exit 0
